development:
  sessions:
    default:
      database: twitter_sentiments_development
      hosts:
        - localhost:27017
      options:
        
  options:
    use_activesupport_time_zone: true
test:
  sessions:
    default:
      database: twitter_sentiments_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

